server:
  port: 8888
springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
spring:
  sql:
    init:
      mode: always
      data-locations: classpath:schema.sql,classpath:data.sql
  session:
    jdbc:
      initialize-schema: always
  jpa:
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create

  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    initialize-mode: always

logging:
  level:
    org:
      hibernate: DEBUG
      type.descriptor.sql.BasicBinder: TRACE
